const { MessageEmbed } = require('discord.js');
const Discord = require('discord.js');
const human = require('humanize');
const paginationEmbed = require('discord.js-pagination');
module.exports ={
    name: 'animalfact',
    description: "An animal fact command",
    aliases: ['animal', 'animalfacts','af'],
    execute(message,args,client){
        

        const Anim = ["Animal Fact - The heart of a shrimp is located in its head.",
        "Animal Fact - A snail can sleep for three years.",
        "Animal Fact - The fingerprints of a koala are so indistinguishable from humans that they have on occasion been confused at a crime scene.",
        "Animal Fact - Slugs have four noses.",
        "Animal Fact - Elephants are the only animal that can't jump.",
        "Animal Fact - A rhinoceros' horn is made of hair.",
        "Animal Fact - It is possible to hypnotize a frog by placing it on its back and gently stroking its stomach.",
        "Animal Fact - Adult cats only meow at humans.",
        "Animal Fact - Nearly three percent of the ice in Antarctic glaciers is penguin urine.",
        "Animal Fact - A cow gives nearly 200,000 glasses of milk in a lifetime.",
        "Animal Fact - Bats always turn left when leaving a cave.",
        "Animal Fact - Giraffes have no vocal chords.",
        "Animal Fact - Kangaroos can't fart.",
        "Animal Fact - An ostrich's eye is bigger than its brain.",
        "Animal Fact - Around 50 percent of orangutans have fractured bones, due to falling out of trees on a regular basis.",
        "Animal Fact - Frogs cannot vomit. If one absolutely has to, then it will vomit its entire stomach.",
        "Animal Fact - Trained pigeons can tell the difference between the paintings of pablo picasso and claude monet.",
        "Animal Fact - Parrots will selflessly help each other out.",
        "Animal Fact - Prairie dogs kiss.",
        "Animal Fact - Ghost crabs growl using teeth in their stomachs.",
        "Animal Fact - The mantis shrimp has the world's fastest punch.",
        "Animal Fact - Female lions do 90 percent of the hunting.",
        "Animal Fact - Narwhal tusks are really an 'inside out' tooth.",
        "Animal Fact - The world's oldest known breed of domesticated dog dates back to 329 BC.",
        "Animal Fact - The oldest evidence of domesticated cats dates back 9,500 years.",
        "Animal Fact - Puffins use twigs to scratch their bodies.",
        "Animal Fact - Bottlenose dolphins are even more right-handed than humans.",
        "Animal Fact - There's a kind of ant that only lives in a small area of Manhattan.",
        "Animal Fact - Cows painted with zebra-like stripes can avoid being bitten by flies.",
        "Animal Fact - Capuchin monkeys wash their hands and feet in urine.",
        "Animal Fact - Sperm whales in the Caribbean have an accent.",
        "Animal Fact - Some pigs in China are the size of bears.",
        "Animal Fact - Some sharks glow in the dark.",
        "Animal Fact - Some snails have hairy shells.",
        "Animal Fact - Cowbirds use secret passwords to teach their young.",
        "Animal Fact - Baby Tasmanian devils make life-long friendships.",
        "Animal Fact - A grizzly bear's bite is strong enough to crush a bowling ball.",
        "Animal Fact - Humpback whales use bubbles to hunt.",
        "Animal Fact - A housefly buzzes in an F key.",
        "Animal Fact - Moray eels have a second pair of 'Alien-style' jaws.",
        "Animal Fact - Ducks can surf.",
        "Animal Fact - Slow lorises are the only venomous primates.",
        "Animal Fact - Pigeons can do maths.",
        "Animal Fact - Zebra stripes act as a natural bug repellant.",
        "Animal Fact - Wild chimps like to drink femented palm sap (monkey alcohol).",
        "Animal Fact - Sea otters are adept at using tools.",
        "Animal Fact - Frogs can freeze without dying.",
        "Animal Fact - Male horses have way more teeth than their female counterparts.",
        "Animal Fact - Koalas sleep up to 22 hours a day.",
        "Animal Fact - A group of ferrets is called a business.",
        "Animal Fact - Octopuses can taste with their arms.",
        "Animal Fact - Dolphins have names for one another.",
        "Animal Fact - Reindeer eyes turn blue in the winter.",
        "Animal Fact - Giraffes have black tongues.",
        "Animal Fact - Alligators will let manatees swim ahead of them.",
        "Animal Fact - Sloths can take up to a month to completely digest a single leaf.",
        "Animal Fact - Elephants and humans have similar self-soothing techniques.",
        "Animal Fact - Female bats give birth to babies that weigh up to a third of their weight.",
        "Animal Fact - Painted turtles survive winter by breathing through their butts.",
        "Animal Fact - Dogs have way fewer taste buds than humans.",
        "Animal Fact - Otters have the world's thickest fur.",
        "Animal Fact - Alligators can grow for more than 30 years.",
        "Animal Fact - A group of owls is called a parliament.",
        "Animal Fact - Snow leopards don't roar.",
        "Animal Fact - Axolotls can regenerate their parts.",
        "Animal Fact - A group of rhinos is called a crash.",
        "Animal Fact - Squirrels will adopt orphans.",
        "Animal Fact - Giant anteaters have two-foot tongues.",
        "Animal Fact - Cows have best friends.",
        "Animal Fact - Moths experience love at first scent.",
        "Animal Fact - Horses have distinct facial expressions.",
        "Animal Fact - Deer can run up to 35 miles per hour.",
        "Animal Fact - An octopus has three hearts.",
        "Animal Fact - Some worms can jump.",
        "Animal Fact - Crocodiles can live up to 100.",
        "Animal Fact - Ravens are masters of deception.",
        "Animal Fact - Rats laugh.",
        "Animal Fact - Tigers have striped skin.",
        "Animal Fact - Cats recognize their own name but choose not to respond.",
        "Animal Fact - Cows produce more milk when listening to slow music.",
        "Animal Fact - Butterflies taste with their feet.",
        "Animal Fact - The spur-winged goose's diet makes it poisonous.",
        "Animal Fact - Vampire bat saliva keeps blood from clotting.",
        "Animal Fact - Giraffes with darker spots are more dominant.",
        "Animal Fact - Orcas can learn to speak dolphin.",
        "Animal Fact - Queen mole rats make other female mole rats infertile.",
        "Animal Fact - Horned lizards squirt blood from their eyes.",
        "Animal Fact - Catfish have taught themselves how to kill pigeons.",
        "Animal Fact - Primitive crocodiles could gallop."
]

        const randomAnim = Anim[Math.floor(Math.random() * Anim.length)];

        message.channel.send(randomAnim + ` - Requested by ${message.author.username}`);
    }
}